const en = {
    name: "English",
    code: "en",
    siteSource: "Site source",
    homePage: "Home",
    about: "About",
    selectLanguage: "Select language",
    back: "Back",
    updated: "Updated on",
    licensedUnder: "Licensed under",
    showNavigationMenu: "Show navigation menu",
    navigationLinks: "Navigation links",
    settings: "Settings",
    siteAvatar: "Avatar of the site owner",
    socialLinks: "Social links",
    blogList: "Blog list",
    externalLinks: "External links",
    search: "Search",
    typeToSearch: "Type to search",
    searchResults: "Search results",
    noResults: "No results",
    clear: "Clear",
    loading: "Loading",
    projects: "Projects",
};

export default en;
