name: End-to-end test
on:
  workflow_call:

jobs:
  test:
    name: Run E2E tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4, 5, 6, 7, 8]
        shardTotal: [8]

    env:
      SHARD_INDEX: ${{ matrix.shardIndex }}
      SHARD_TOTAL: ${{ matrix.shardTotal }}

    environment: test

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: e2e:latest

      - name: Run tests
        uses: addnab/docker-run-action@v3
        with:
          image: e2e:latest

      - name: Upload blob report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: blob-report-${{ matrix.shardIndex }}
          path: blob-report
          retention-days: 1

  merge_reports:
    if: ${{ !cancelled() }}
    needs: [test]

    runs-on: ubuntu-latest
    name: Merge Playwright reports

    steps:
      - uses: actions/checkout@v4

      - name: Set up
        uses: ./.github/workflows/setup-action

      - name: Download blob reports
        uses: actions/download-artifact@v4
        with:
          path: all-blob-reports
          pattern: blob-report-*
          merge-multiple: true

      - name: Merge into HTML Report
        run: bun playwright merge-reports --config=playwright-merge.config.ts ./all-blob-reports

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: html-report--attempt-${{ github.run_attempt }}
          path: playwright-report
          retention-days: 30
