name: IndexNow
on: 
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  check-and-submit:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Submit URLs to IndexNow
        uses: bojieyang/indexnow-action@v1
        with:
          sitemap-location: https://thejiahao.github.io/zh-cn/sitemap.xml
          key: ${{ secrets.INDEXNOW_KEY }}
          key-location: https://thejiahao.github.io/IndexNow-${{ secrets.INDEXNOW_KEY }}.txt
          failure-strategy: error
          endpoint: api.indexnow.org
